begin;

create table public.notification_delivery_logs (
  id bigint generated by default as identity primary key,
  information_request_id uuid
    references public.information_requests(id)
    on delete set null,
  provider text not null
    check (provider in ('telegram')),
  event_type text not null
    check (event_type in ('information_request.insert', 'test')),
  status text not null
    check (status in ('sent', 'failed')),
  provider_message_id bigint,
  http_status integer
    check (http_status is null or http_status between 100 and 599),
  error_message text
    check (error_message is null or char_length(error_message) <= 1000),
  payload_summary jsonb not null default '{}'::jsonb,
  attempted_at timestamptz not null default now()
);

create index notification_delivery_logs_request_idx
  on public.notification_delivery_logs (
    information_request_id,
    attempted_at desc
  );

create index notification_delivery_logs_failed_idx
  on public.notification_delivery_logs (attempted_at desc)
  where status = 'failed';

alter table public.notification_delivery_logs enable row level security;

create policy "Active admins read notification delivery logs"
on public.notification_delivery_logs
for select
to authenticated
using (public.is_active_admin());

revoke all on public.notification_delivery_logs
from public, anon, authenticated;

grant select on public.notification_delivery_logs
to authenticated;

comment on table public.notification_delivery_logs is
  'Server-side Telegram notification delivery results. Inserts are performed only by the Edge Function service role.';

comment on column public.notification_delivery_logs.payload_summary is
  'Operational notification metadata only. Visitor email and cellphone must never be stored here.';

create or replace function public.notify_new_information_request()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_webhook_secret text;
  v_pg_net_request_id bigint;
begin
  begin
    select decrypted_secret
    into strict v_webhook_secret
    from vault.decrypted_secrets
    where name = 'telegram_webhook_secret';

    select net.http_post(
      url := 'https://myqaotknkriuhdssbzlz.supabase.co/functions/v1/notify-new-request',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-webhook-secret', v_webhook_secret
      ),
      body := jsonb_build_object(
        'type', 'INSERT',
        'schema', TG_TABLE_SCHEMA,
        'table', TG_TABLE_NAME,
        'record', to_jsonb(NEW)
      ),
      timeout_milliseconds := 5000
    )
    into v_pg_net_request_id;
  exception
    when others then
      raise warning
        'Telegram notification enqueue failed for information request %: %',
        NEW.id,
        SQLERRM;
  end;

  return NEW;
end;
$$;

revoke all
on function public.notify_new_information_request()
from public, anon, authenticated;

drop trigger if exists notify_new_information_request
on public.information_requests;

create trigger notify_new_information_request
after insert on public.information_requests
for each row
execute function public.notify_new_information_request();

commit;
